/**
 * @module setup/env-file
 * @description Minimal .env read/merge/write helpers shared by the setup scripts.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

/** Walk up from this module to find the project root (nearest package.json). */
export function findProjectRoot(): string {
  let dir = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 8; i++) {
    if (existsSync(resolve(dir, 'package.json'))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return process.cwd();
}

/** Parse a .env file into a flat key/value map (ignores comments and blanks). */
export function parseEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) return {};
  const out: Record<string, string> = {};
  const content = readFileSync(path, 'utf-8');
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    // Strip surrounding quotes if present.
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (key) out[key] = value;
  }
  return out;
}

/**
 * Merge `updates` over the existing .env at `path` and write it back.
 * Empty-string values are dropped (so you can clear a key by passing '').
 */
export function writeEnvFile(path: string, updates: Record<string, string>): void {
  const merged: Record<string, string> = { ...parseEnvFile(path), ...updates };
  const lines: string[] = [
    '# Email AI Agent — generated by the setup wizard',
    `# ${new Date().toISOString()}`,
    '',
  ];
  for (const [key, value] of Object.entries(merged)) {
    if (value === '' || value === undefined) continue;
    // Quote values containing spaces or shell-significant characters.
    const needsQuote = /[\s#"'$]/.test(value);
    lines.push(`${key}=${needsQuote ? JSON.stringify(value) : value}`);
  }
  writeFileSync(path, lines.join('\n') + '\n', { encoding: 'utf-8' });
}
